### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by atlet**
Merging...

### CODE REVIEW

**Comment by dasistwas** [comment]
Hi,

I think this needs careful manual checks in order to merge everything properly. I added a lot of features, which will result in conflicts in many files. Which is not so cool, is that there are so many parts of the code, which are only different in formatting and not in actual code. So it would be cool to have the same code formatting style and not to change formatting on unchanged code. Attached you will find 
the code style for eclipse neon.3
[Moodle code style.txt](https://github.com/atlet/moodle-mod_booking/files/941367/Moodle.code.style.txt)

You have to rename txt to xml as github does not allow xml uploads.

Kind regards,
Davdi

**Comment by atlet** [comment]
Yes, I'm looking at it. :( Do you have cooding style for Netbeans?

**Comment by dasistwas** [comment]
Hi,
Netbeans coding style is there: https://github.com/enovation/moodle-utils/tree/master/netbeans-config
Docs for setting up Netbeans with Moodle is there: https://docs.moodle.org/dev/Setting_up_Netbeans

**Comment by dasistwas** [comment]
Another comment on merging your additions:

The merge at https://github.com/dasistwas/moodle-mod_booking/compare/master...atlet:develop seems to look quite good. Still a view problems remain:

- db/install.xml: Would be cool to checkout from my develop branch again, and just add the new field, do not format the whole file

- db/upgrade.php: There are several problems. Please checkout my dev and add your additional field with ` if ($oldversion < 2017042100) {`
https://github.com/dasistwas/moodle-mod_booking/compare/master...atlet:develop#diff-c74097fbb0a2db56a0a98aaf7d6a2654R1429
The version has to be a more recent date, otherwise those who installed the latest release won't add the additional field in the db.
Also the code added at https://github.com/dasistwas/moodle-mod_booking/compare/master...atlet:develop#diff-c74097fbb0a2db56a0a98aaf7d6a2654R416 is obsolete
- New help text ist not necessary, use the old one. This would just be a duplicate text, not necessary
$mform->addHelpButton('daystonotify2', 'daystonotify2', 'booking'); 
daystonotify2 -> daystonotify

**Comment by atlet** [comment]
Ok, I fixed all 3 issues, I hope now it's ok.

**Pull request merged**
